site_name: ukulib docs
repo_url: https://github.com/uku3lig/ukulib
repo_name: uku3lig/ukulib
nav:
  - Home: index.md
  - Setup: setup.md
  - Config:
      - Introduction: config/index.md
      - Configuration screens: config/config-screen.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  features:
    - navigation.tabs
  language: en
  logo: assets/icon.png
  favicon: assets/icon.png
  font:
    text: IBM Plex Sans
    code: Iosevka
  palette:
    # allow automatic color switch
    - media: "(prefers-color-scheme)"
    # light and dark mode settings
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
